# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        profile.pictures.storage:
            adapter: 'asyncaws'
            options:
                client: 'scaleway_object_storage_client'
                bucket: '%env(SCALEWAY_OBJECT_STORAGE_BUCKET)%'
